### ISSUE TITLE
parser: initialize struct with values

### ISSUE THREAD

**Issue by zegl** [zegl/tre#9]
https://gobyexample.com/structs

```go
foo := Bar{
    a: 123,
    b: 123,
}
```

**Comment by mewmew** [comment]
It is by intention to deviate from the Go syntax on this?

```go
foo := &Bar{
    a: 123,
    b: 123,
}
```

**Comment by zegl** [comment]
Hej Robin,

Thanks for checking out the project. I created this issue before I changed my mind and decided to use the same syntax as Go in tre. The description has been updated.
